
== 什么是开源共同体？

根据开源之道的定义如下：

> **为了实现一个开源软件项目，基于互联网，由企业、个人、非营利组织等形成的团体成员（接受过现代计算机科学的训练），在文化上能够达成一定共识，来去自由，进行一定的社会治理、活动、交流等，所形成的合作共同体。**

既然为一个社会现象下了一个定义，那么我们就需要为之进行代入式的解释，那么具体的、典型的开源共同体有那些，笔者在这里给大家根据不同的类型进行概要的介绍，不过首先提醒大家的是，开源的共同体大大小小的，犹如现实生活中的生活社区，非常之多，错综复杂、纵横交错，

=== GNU GCC

=== Linux Kernel

=== Apache HTTPD

=== Python

=== Debian

== 开源共同体的角色构成

作为一个存在的社会团体，了解其内部的角色分类是必须要做的事情，否则就无法进一步了解和参与。组成社会团体的是每一个个体，这些个体恰是作为开源发起者特别需要争取的对象，但是对于某一类文化来说，比如奉行集体主义的东方文化里是极难发展个体的，必要的时候还是要将目光
转向某些小型的组织，哪怕是三三两两的同学也好。（有心的读者可以留意一下本土的开源发展的，往往是某个高校如西安邮电、兰州大学等，往往是一拨一拨的。是非常值得探究的现象。）

=== 开源共同体中的作为个人的角色分类

==== 领袖

在人类的历史上，从来就不曾缺失过哪些一心致力于自身对于事物的驾驭的追求与能力，古希腊戏剧《普罗米修斯》或者是罗马的建筑大师维特鲁威，在开源共同体中，也不乏这样的人，我们这里不妨列举几位：

* 林纳斯·本纳第克特·托瓦兹（Linus Benedict Torvalds），Linux和Git创始人
* Larry Well ,Perl 语言创始人
* Tim O’Reilly ， “open source” 一次的推动者，出版了数以千记的开源技术、文化相关的图书
* Guido van Rossum Python 语言创始人
* Brian Behlendorf  Apache 基金会创始人之一，Apache web服务器主要发起者
* Eric Raymond ，著名书籍《大教堂与集市》的作者，OSI 的发起者之一
* Jim Zemlin Linux基金会执行董事
* Henry Zhu Babel  项目维护者
* .......

更多开源共同体中的领袖或Hero们，请关注开源之道的系列文章:

*  http://www.opensourceway.community/posts/opensource_leader/bruce_perens_open_source_definition/[Bruce Perens，向全世界宣布“开源”的人]
*  http://www.opensourceway.community/posts/opensource_leader/solomon_hykes_and_the_docker_revolution/[开源英雄：Solomon Hykes和Docker的革命性崛起]

==== 核心贡献者

每一款开源项目，除了发起者之外，都有核心的贡献者参与，或者提供设计、代码补丁、文档撰写，这是构成开源共同体的核心主力，换句话说：**如果不能理解核心贡献者，那么就无法理解开源共同体**。他们是主要的生产力！

想要了解项目的核心贡献者，分为两步：

1. 到每个开源项目的发布版本日志里，找出贡献者名单。
2. 下载源代码，使用版本控制系统，如```git shortlog -c``` ，对应出名字来
3. 根据2找到ta写的代码、注释、设计
4. 只有理解了3，才能感同身受地体会ta解决问题的过程，以及为这个问题所花费的时间和精力。

==== 律师

在自由/开源软件发展的历史上，知识产权相关发挥了重要的作用，也就是说法律才是开源的支柱，在这个共同体当中，维护者开发者的权益，至少不被侵犯，从天才般的Richard Stallman 创立的GPL ，到各式各样的许可证，以及OpenChain、开放发明网络（OIN）等机构的诞生。

法外之地，开源将不复存在，因为这是人类的高等文明，需要克服人类基本之人性。律师帮助我们、一路同行，做到了这一点。他们是这个开源共同体中不可或缺的重要角色。

==== 拥护者和布道师

这个世界需要诉说者，著名作家伍尔夫写过“没有被叙述的就等于没有发生过”，开源想要联结成为强大的共同体，最终展现在世人面前“可见的”，是能够提供实用功能的运行在计算机当中的软件，不是每个人都具备上述探索核心贡献者，评估他们的工作成果的能力的。那么传播开源、宣扬开源价值的人就有了ta存在的意义。而随着开源在社会中的地位提升，做这些事的人也越来越紧俏。

关于布道的意义，在此我想没有比法国著名社会学者托克维尔在《论美国的民主》一书中所描述的更为精准的了：

> 一个社团要想有力量，就必须人多。而由于成员的人数太多，所以他们只能分散在广大的地区，每个人仍然要留在原来的地方，去过他们的哪种比上不足比下有余的生活，为成千上万的小事而操劳。因此，他们必须找到一个使他们不用见面就能彼此交谈不用开会就能得出一致意见的手段。这个手段就是报刊。

对比我们现在所处的互联网时代，报刊替换为媒体：社交平台、即使聊天、邮件列表等更为先进的媒介手段！

==== 用户

根据开源共同体的定义，这里的用户，我们要除却不懂计算机的其它行业的人士，在如今的信息社会，几乎没有人不是开源软件的使用者，我们如果把这个定义套用到他们身上的话，那简直是过于泛泛了，所以我们这里要区别出来：

**知道自己在有意的使用开源软件，或自行编译开源项目的用户**，最重要的是这些用户在选择软件的时候，会偏向使用开源软件，或者是因为经济、法律、喜好、社交等原因。无论是处于什么原因在使用开源软件的人，意识到自己在使用这种属性至关重要，这里主要是想和盗版区别开来。

软件生产出来就是被人用的，如果一款软件没有用户，那么就其意义就需要另外商榷。

==== 搭便车者

我们不可以强制要求邻居或朋友参与到贡献当中来，或者通过劝诱、胁迫等手段去要求ta人。

如果光是用户也还罢了，开源软件是可以解决一些实际问题的，一旦能够解决实际问题，那么它就有了经济利益，那么如果这些人，利用了开源项目，有了其它的商业目的，做了类似投机倒把的事情，那么我们不妨称这类人为搭便车者。

现实中的搭便车者，比比兼是，由于软件的商业创新，使用的是信息授权模式，所以将开源项目编译为二进制软件之后，是有商业利润存在的。但是呢，这些人虽然从中渔利了，但是并没有考虑其所利用的开源项目的持续性发展的问题，无论是人员的投入，还是金钱上的支持，甚至是宣传活动也是掩盖的。有的时候，一眼就可以看出来，有的时候却需要内行人去仔细的甄别。

==== 反对者

反对开源的人也不在少数，尤其是传统上利用专有软件授权赢得了非常高的利润的公司的员工，称开源软件为“搅屎棍”，损坏了他们的利益，违反了知识产权，最有名的就是微软公司的第二任CEO 史蒂夫·鲍尔默（Steve Ballmer）称Linux为癌症的论断了。

这里笔者想阐述一个特别的群体，那就是盗版者，由于开源的免费特性，会让传统专有软件授权的盗版者打着开源的名义堂而皇之的进行专有软件的盗版行为，以迷惑用户，或者以低于专有软件价格很多倍的形式进行非法行为。这其实也是开源的反对者，而且这个更具破坏力，主要是混淆视听。从道德上讲这一类人是要被谴责的，在法律上讲是严重的违法。

==== 开源相关研究的学者

就开源这个现象而言，它太过于迷人，以至于很多学科的学者们都为之倾倒，经济学、社会学、人类学、软件工程、心理学、管理、法律等诸多学科都在围绕开源这个主题进行相关的拓展和研究，有兴趣进一步研究的读者可以关注[开源之道论文阅读计划](https://github.com/OCselected/ttoos/projects/8)，会涉及到很多相关论文的阅读和作者们的介绍。

目前整理成册的开源研究论文集，可以参考开源之道图书共读2019年11月的图书：[Perspectives on Free and Open Source Software (The MIT Press)](posts/paper_or_book_reading/book_review_of_mitfoss/)，聪明的读者你可以顺藤摸瓜，可以找到各位教授在自己的领域里就开源这个主题所研究的成果，如Audris Mockus、Siobhan O’Mahony、Eric von Hippel......

另外国内的学者大家可以关注北京大学周明辉教授、华东师范大学王伟老师、南京大学王宇、以及国防科技大学研究集体智慧的几位学者。

=== 开源共同体中的作为机构的角色分类

==== 拥抱开源的商业公司

有了上面个人的理解，再来理解商业公司就会好很多。一个主要的甄别点就是，商业公司直接雇佣核心贡献者或项目领袖，让这些人发挥自己的智力和能力，至于商业公司如何赢得商业利益，那是另外一件事情，这方面做的非常不错的公司，首屈一指的就是 RedHat 公司，当然还有互联网巨头如Google、Facebook、Linkedin、Netflix等。

也就是说，一家商业公司是否为开源共同体中的好公民，也是靠其员工的贡献值来进行衡量的。千万不要以为是PR就可以，将自己嘴上吹个天花乱坠，然而没有实质的贡献，那纯粹是扯淡。

==== 为项目共同体服务的基金会或类似机构

开源项目的共同体是一个基于互联网的虚拟组织，并不具备现实的法律实体，也就是说当项目需要资金、或者权益受到伤害到时候，在国家这个层面上，是没有可以维护的，尤其是涉及到多人的时候，然而，这个共同体主要是生产软件的，很多其它的社会性事务是不擅长的，比如组织会议、法律、接受捐赠、寻求赞助等等。那么这样的服务机构应运而生。

==== 打压开源的商业公司

从比尔.盖茨参加完家酿俱乐部之后发表的《至电脑爱好者的一封信》之后，软件以二进制分发授权的商业模式一发不可收拾，至今仍然是软件商业帝国大厦的支柱。

和很多事物一样，如果有了替代品，威胁到了既得利益者，那么这些既得利益者就会打压，其中以微软臭名昭著的“万圣节备忘录”为最，当然Oracle也是坚定的打击开源的厂商之一，收购SUN公司之后，一系列开源项目被迫停止开发就是例证。

还有就是公有云提供商，采用完全兼容开源的模式，对开源进行一些锁定的定制，然后通过捆绑的方式来进行销售相关计算、存储、网络资源。这些云厂商未必对开源共同体有贡献，但是它可以进行下游的定制，这其实是在削弱开源共同体，搞到开源项目不可持续。这些云提供商是实至名归的打压开源的商业公司！作为消费者其实应该认识到这一点。

==== 行走在开源和专有软件授权模式之间的灰色地带

上面提到，软件以二进制分发授权的商业模式已经发展了近40多年了，绝大多数以及主流媒体都对这样的模式是视之为默认的，那么开源的商业创新其实产生革命性的变化可能性不太大，那么介于这二者之间的，必然是大家都能够接受的方式，比如2019年开始火起来的“Open Core”模式，这个模式不能说是开源，但也不能说和开源没有开源，它确确实实是部分开源了，只是在功能或性能上商家做了区分。分两步走：

1. 依靠开源软件的分发渠道和模式，让用户消费者适应，并产生锁定。
2. 再更一步的模式采用授权模式

==== 脱离开源共同体的商业公司开源

开源共同体，是一个想象中的概念，现实当中并没有一个类似政府的机构代表这一实体，也就是说，任何人都可以称自己是开源的一份子。那么对于商业公司来讲，搭上开源分发的便车是个不错的营销手段，那么就有很多新的公司有效的利用到了这点，它有可能是刚刚打进软件这个市场，并没有在技术上和开源共同体形成一个有效的技术栈（参考上面提及的产业链的视角看开源软件），或者说在现有的开源共同体中是一个新的实体，从来没有人听说过他们，他们也没有对现有的共同体下的项目做任何的贡献。即使是这样，他们“开源”自己的产品，使自己始终处于游离的状态，使自身是处于一种“孤岛”的状态，虽然开源了，但是并没有融入到开源共同体当中，从技术、文化等诸多角度来看都是。

这类公司，我们也会常常遇到，大多是创始人在遇到经营困难的时候，突发奇想，对众包、免费劳动力、庞大的消费者群体等吸引，于是，幻想着自己的产品能够通过他们自己理解的开源一炮打响。这些人当然往往也找不到宣传的途径，最明显的特征就是寻找传统的媒体来进行PR，然而也只是共同体之外的人看热闹而已。对于开源共同体来讲，这些所作所为显然不是他们所关心的内容。

== 开放式开发平台的崛起

当然，伴随着开源的崛起，大大小小的开源共同体所生产的开源项目水涨船高，逐渐的开始被社会所认可，并获得了更多的资助。那么人类这么聪明的物种，从来不会放过任何能够可以复制成功的机会。于是有人开始总结开源项目的开发模式，并进行了整理。并开发了相应的平台：

* GitHub
* LaunchPad
* Gerrit
* https://pagure.io/[Pagure]
* Trac

等平台的开发模式，上述这些平台基本会覆盖软件开发中所有的系统，而且还和其它系统有着友好的集成。GitHub 我们在本书中会进行专门的叙述，请移步[GitHub 详解]，其它平台我们就在这里给大家简单的叙述一番。


== 开源社交礼仪

因为是共同体，没有强约束关系，所以全凭是人类的高级认知来进行沟通、协商，进而形成默契。所以一些基本的，人类进化到目前为止的所有优秀的内容都应该在此得到最好的展现。

== Community (共同体)治理模型



== 开源开发协作流程



== 维护者的最佳实践


== 参考资料
