
> 本章将以举例的方式说明，一篇优质的贡献者指南应该有哪些内容，而且会举出一些业界典范。本文档大部分来源于 Nadia eghbal 所写就的 https://github.com/nayafia/contributing-template[贡献者指南模板] 并做了适当的补充。

==== 介绍

===== 在此写一些友好的内容！

> 首先，非常感谢你正在考虑为 Active Admin 进行贡献，没错，正是像你这样的人打造了 Active Admin 这么精良的工具。

来自 https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md[Active Admin] 贡献者文档

更多优秀的项目介绍说明，请参考 <<参考文档>> 中的[1]和[2]

===== 告诉人们为什么应该读向导

>  了解向导的内容，有助于你和开发者的沟通，可以有效节省该开源项目的开发者管理和开发的宝贵时间。作为回报，他们会在回复你的issue、评估变更、以及完成你的 Pull Request 给予同样的尊重。

内容来自 https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md[Hoodie] 贡献者文档

===== 解释你期望的贡献类型

保持开放的头脑！改进文档、bug 筛选、以及为任何有用处的贡献撰写教程，都会大大的减轻维护者的工作量。

[NOTE]
====
ElasticSearch 是一款开源项目，而且我们非常热心的希望收到来自共同体的——你——的贡献！有很多种路径实现贡献：撰写教程、撰写博客、改进现有文档、提交bug报告、提交新功能需求、以及提交代码，均是为 Elasticsearch 自身内部合作的一部分。
====

内容来自 https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md[Elasticsearch] 贡献者文档，更多优秀的解释贡献类型说明，请参考 [参考文档] 中的 <<3>> 和 <<4>>

===== 解释你不想看到的贡献类型（如果有的话）

再重复一遍，做这些工作可以大大的减轻维护者的工作量。如果有人忽略掉你的向导指南，并提交了一些你最不想看到的内容，那么这个时候你就可以正当的关闭它，并告诉ta你的规程。

TIP: 请不要使用 issue 跟踪来获得问题支持。请到 Freenode 上的 IRC 频道找 #pocoo 来进一步获得支持。如果你的问题不是直接和 Werkzeug 或 Flask 相关，#python 频道是非常活跃的有可能帮到你的，另外 Stack Overflow 也非常值得考虑。

内容来自： https://github.com/pallets/flask/blob/master/CONTRIBUTING.rst[flask] 贡献者文档，更多优秀说明，请参考 <<5>> 和 <<6>>。

==== 基本规则

===== 设定期望的行为（你的和他们的）

此处的信息不仅包括如何和他人沟通（彼此尊重、考虑对方等），也要包括技术上的责任（测试的重要性、项目依赖等），如果有行为准则的话，提示并将链接地址释出。

IMPORTANT: 责任:

 -  确保每次变更跨平台的兼容性都能被接受：Windows、Mac、Debian& Ubuntu Linux。
 -  确保进入核心的代码满足检查表中的所有要求: https://gist.github.com/audreyr/4feef90445b9680475f2
 -  任何主要的变更和改进都要创建issue，以透明的方式进行讨论，且要获得共同体的反馈。
 -  除非是绝对必要的情况下，否则不要为代码增加新的类，Err on the side of using functions.
 -  尽可能的保持特性版本最小化，理想的情况是一个版本只有一个特性。
 - 对新来这表示友好！鼓励多样性，任何背景的贡献者都是欢迎的。请参考 https://www.python.org/psf/codeofconduct/[Python 共同体行为准则]。

内容来自： https://github.com/audreyr/cookiecutter/blob/master/CONTRIBUTING.rst[cookiecutter] 贡献者文档，更多优秀说明，请参考 <<7>> 和 <<8>>。

==== 针对初次贡献的说明

帮助刚刚接触到贵项目的新人，最佳之处就是了解他们哪里需要帮助。而这通常也是一个展示你项目是否适合新手的好时机。

例如 https://github.com/atom/atom/blob/master/CONTRIBUTING.md#your-first-code-contribution[Atom] 给出贡献者指南：

TIP: 不确定如何开始为 Atom 做贡献？你可以先从那些标记为 beginner 或 help-wanted的issue入手：
Beginner issues -  那些只需要几行代码就可以搞定，或者是做一到两个测试的 issues 。
Help wanted issues - 比 Beginner 更深度参与的 issues 。
上述 issue 列表，你可以将之按评论总数排序。虽然这么做有所缺陷，但是评论的数量可以合理地反映一个给定的变化将会产生的影响。

这就非常的清晰了，更多的优秀的关于针对首次贡献的说明，可参考：<<1>>、<<9>>

==== 为从来都没有为开源贡献过的人添加资源链接

这里有一些友好的教程或许有所帮助：

* http://makeapullrequest.com/[]
* http://www.firsttimersonly.com/[]

TIP: 正在为你的第一个 Pull Request 做准备吗？你可以从这个系列文章中学习到： https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github[在 GitHub 如何为开源项目做贡献]

以上内容是 https://github.com/facebook/react/blob/master/CONTRIBUTING.md#pull-requests[React] 项目所提供的额外资源。简直是良心共同体。

==== 贡献者入门指南

===== 给出如何提交贡献的快速路径

这部分的内容如何写取决于你自己，不过下面的内容最好是包含进来：

* 告诉众人他们需要签署 CLA，同意 DCO，以及其它法律上的事情
* 如果贡献需要测试，也让他们知道，并解释如何跑测试
* 如果你使用了GitHub之外的issue管理工具（如JIRA、Trac），也请告诉他们如何去提交贡献

TIP: 针对修改一两行内容之上的改动，应做到：

1. 将代码fork到自己的账户
2. 在自己的代码中进行修改
3. 如果你认为修改很完善，且项目应该接受的话，要做到：
   * 确保代码风格是和项目一致的。
   * 和 jQuery 基金会签署了贡献者许可协议（CLA）
   * 知晓 jQuery  基金会的行为准则
   * 发送的 Pull Request 里包含 CLA 文件

以上是来自 http://requirejs.org/docs/contributing.html[requierjs] 贡献者指南的良好实例，另外有心的读者还可参阅 <<10>> 、 <<11>> 和 <<12>>。

===== 如果您对小的或“明显的”修复有不同的流程，请让他们知道

关于此方面， https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-obvious-fix-policy[chef] 有着非常不错的描述

> 小的贡献(比如修正拼写错误)，其内容小到不属于知识产权，可以由贡献者作为补丁提交，而不需要签署 CLA。

> 根据经验，如果更改没有引入任何新功能或创造性思维，那么更改就是明显的修复。只要更改不影响功能，一些可能的示例包括:

* 拼写、语法错误修正
* 单词更正、空格和格式的变更
* 注释清理
* 变更返回值或者静态存储了错误的代码的Bug修复
* 增加日志信息或 debug 的输出
* 改动‘元数据’文件，如 Gemfile、.gitignore、构建脚本等。
* 从一个目录或包移动文件到另外的目录或包

另外也可参考 <<13>> 即Puppet 的做法。

==== 如何报告缺陷

===== 说明披露安全问题是的首要法则

至少，包括以下句子:

> 如果你发现了安全漏洞，请不要新建 issue，请发送 Email 给 xxx。

如果你不想使用自己的个人联系信息，那么需要开通“security@”的邮箱地址。更大一点的项目需要更多正式的流程来处理安全披露，如加密通信等。

> 任何事关安全的 issue 请直接提交到 security@travis-ci.org

> 为了确定自己是否在处理安全问题，请问自己以下两个问题:

> * 我可以访问不是我自己的内容吗？或者说我应该访问吗？
> * 我可以将其他人禁止使用吗？

> 如果以上两个问题的任何一个问题的答案是”是“的话，那么就可以认为这是一个安全问题。

> 提示：即使以上两个问题回答均为”否“，也不代表你处理的不是安全问题，实在确定不了的话，还请直接发送问题给security@travis-ci.org。

https://github.com/travis-ci/travis-ci/blob/master/CONTRIBUTING.md[Travis-CI] 给了我们一个非常好的例子，另外 <<14>> 、<<15>> 也不错。

===== 告诉你的贡献者如何撰写bug 报告

你可以准备好一些模板，这样人们就可以复制-粘贴（呵呵，再次节省你的工作）。Go 语言给了我们非常不错的范例：

> > 当提交一个issue，请确保回答了以下这五个问题：
>
> 1. 你使用的是Go的哪个版本（`go verison`)?
> 2. 使用的是什么处理器架构以及操作系统？
> 3. 你做了什么？
> 4. 你原本期望是什么？
> 5. 实际运行的结果？
>
> 一般的问题请到 golang-nuts 邮件列表中，而不是在此issue跟踪，在那里 gopher 们会很好的回答你的问题。

更多bug报告经常的描述，可参考 <<14>> 和 <<16>>。

==== 如何为新的功能和改进提建议

===== 如果有特定的 roadmap、目标、原则、开发方式等，分享到这里

这些信息可以帮助到贡献者了解上下文，进而避免他们提出不符合项目需求的建议。（节省彼此的时间）

> Express 的哲学思想是为 HTTP 服务提供小巧的、稳定的工具集，为单个页面应用、web站点、混合、或者是公开的 HTTP API提供伟大的解决方案。

> Express 不会强制你使用任何特定的ORM 或模板引擎，通过Consolidate.js ，Express 提供了超过14中模板引擎，你可以快速的构建自己的完美框架。

https://github.com/expressjs/express#philosophy[Express.js] 这份原则声明就为我们提供了非常好的例子，<<10>> 做的也非常不错，供参考。

===== 解释建议某个特性所需的过程

如果是前后来回需要确认的话，那么这个解释就很必要了。询问他们功能的范围，仔细思考为什么这个功能是必须的，以及其将如何工作。

> 如果你发现了Elasticsearch没有你意想中的功能，你并不是第一位，也不是最后一位，请相信自己，一定会有其他有类似需求的人。Elasticsearch 有很多功能都是因为用户的需要而增加的，请在GitHub上新建一个issue，描述清楚你需要的功能，以及为何需要它，最好也描述一下它应该如何工作。

来自 https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#feature-requests[Elasticsearch] 的实例。更多精彩请参考 <<17>>、<<18>>。

==== 代码核对（review）流程

===== 解释代码提交之后如何能够被接受的全过程

谁来核对？在被接受之前需要谁的签名？贡献者希望在什么时候收到你的消息?贡献者如何获得提交访问(如果有的话)?

> 我们的核心团队会在每周的分类会议上查看 Pull Requests，会议是使用公开的Google Hangout进行。每周状态更新会发送到 puppet-dev 邮件列表。所有的注意事项都会记录到 Puppet 共同体 community-triage仓库，Hangout 同时也会上传到YouTube上。

> 在收到反馈后，我们期望在两周内得到答复。两周后，如果没有显示任何活动，我们可能会关闭 pull request。

https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md#submitting-changes[Puppet] 为我们提供了非常好的范例。另外也可参考 <<15>> 和 <<19>>。


==== 共同体（community）

如果你的项目除了 GitHub 之外还有其它的通道的话，一并在这里列出。还可以作者、维护者、亦或是贡献者都可以写上，或者是说明一下响应时间的期望。

> 你可以来 https://gitter.im/cucumber/cucumber 和我们的核心团队接触，我们会在周五提供专门的时间。

https://github.com/cucumber/cucumber-ruby/blob/master/CONTRIBUTING.md#talking-with-other-devs[cucumber-ruby] 就是最好的例子。另外也可参考 <<20>> 和 <<21>>。

===== 可选：代码、commit 约定、以及标签约定

以下这些内容并非必须项，但是对于简化贡献的流程等内容会有所帮助的。

===== 解释项目有特别的代码风格，如果有的话。

可参考：<<22>> <<23>>

===== 如果项目采用了一定的 commit 约定的话，请解释一番

可参考：<<24>> <<25>>

===== 如果项目的 issue 采用了标签约定的话，请解释一番

可参考：<<26>> <<27>>

====== [参考文档]

[1].  http://read-the-docs.readthedocs.org/en/latest/contribute.html[Read The Docs] 贡献者文档

[2].  https://github.com/janl/mustache.js/#contributing[Mustache.js] 贡献者文档

[3]. https://github.com/plataformatec/devise/wiki/Contributing[Devise] 贡献者文档

[4]. https://github.com/alexreisner/geocoder#known-issues[Geocoder] 贡献者文档

[5]. https://github.com/cucumber/cucumber-ruby/blob/master/CONTRIBUTING.md#about-to-create-a-new-github-issue[cucumber-ruby] 贡献者文档

[6]. http://read-the-docs.readthedocs.org/en/latest/open-source-philosophy.html#unsupported[Read the Docs] 贡献者文档

[7]. https://github.com/celery/celery/blob/master/CONTRIBUTING.rst#community-code-of-conduct[Celery] 贡献者文档

[8]. https://github.com/alexreisner/geocoder#contributing[geocoder] 贡献者文档

[9]. https://docs.djangoproject.com/en/dev/internals/contributing/new-contributors/#first-steps[Djongo] 贡献者文档的向导部分

[10]. https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#1-where-do-i-go-from-here[Active Admin] 贡献者文档

[11]. https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#code-contributions[node.js] 贡献者文档

[12]. https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#pull-requests[Ember.js] 贡献者文档

[13]. https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md#making-trivial-changes[Puppet] 贡献者文档

[14]. https://github.com/celery/celery/blob/master/CONTRIBUTING.rst#security[Celery] 贡献者文档

[15]. https://github.com/expressjs/express/blob/master/Security.md[Express.js] 贡献者文档

[16]. https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs[Atom] 贡献者文档中关于报告 Bug 的部分

[17]. https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md#feature-requests[Hoodie] 贡献者文档

[18]. https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature[Ember.js] 贡献者文档提交功能需求

[19]. https://meteor.hackpad.com/Responding-to-GitHub-Issues-SKE2u3tkSiH[Meteor] 代码review

[20]. https://github.com/chef/chef/blob/master/CONTRIBUTING.md#-developer-office-hours[chef] 开源共同体

[21]. https://github.com/audreyr/cookiecutter#community[cookiecutter] 开源共同体说明

[22]. http://requirejs.org/docs/contributing.html#codestyle[requirejs] 代码风格指南

[23]. https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-to-the-elasticsearch-codebase[elasticsearch] 代码风格指南

[24]. https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#submit[Angular] 的提交Commit注意事项

[25]. https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#step-3-commit[Node.js] 的提交Commit注意事项

[26]. https://github.com/wagenet/StandardIssueLabels#standardissuelabels[StandardIssueLabels] 标签约定

[27]. https://github.com/atom/atom/blob/master/CONTRIBUTING.md#issue-and-pull-request-labels[Atom] 标签约定做的非常不错。
