[glossary]
= 名词解释

== 开源 （Open Source）

开源隶属于开放这个大的范畴，意指一款产品或制品，其不仅提供最终可用的实体，还应该提供源代码、设计文档、交流过程等，最初的意思来自于[#开源软件]的模式，随着开源软件运动的逐步胜利
和崛起，开源这个词汇的范畴也在扩大，在社会中的其它行业也有了较为广泛的应用，如开放式协作、开放内容、开放设计等。

在中国本土，开源还有另外的一个意思：“开源节流”，通常指的是让自己的收入有尽可能的多样化，与非软件行业的人交流的时候要特别的注意。

==  开源软件（Open Source Software）


我们这次选择了两种解释风格，一种是正式的、举世公认的定义，即开放源代码促进会（Open Source Initative)的定义：

1. 自由再发布
2. 源代码
3. 派生作品
4. 作者源代码的完整性
5. 不能歧视任何个人和团体
6. 不能歧视任何领域
7. 许可证的发布
8. 许可证不能针对某个产品
9. 许可证不能约束其他软件
10. 许可证必须独立于技术

可参考： https://opensource.org/osd[OSI定义]。

另外一个就是较为通俗的版本，引用自 https://zh.wikipedia.org/wiki/%E5%BC%80%E6%BA%90%E8%BD%AF%E4%BB%B6[Wikipedia]：

"```又称开放源代码软件，是一种源代码可以任意获取的计算机软件，这种软件的著作权持有人在软件协议的规定之下保留一部分权利并允许用户学习、修改以及以任何目的向任何人分发该软件。
开源协议通常符合开放源代码的定义的要求。一些开源软件被发布到公有领域 开源软件大多采用公开协作的方式进行开发，开源软件是开放式协作的典范。开源软件是开放源代码开发的最常见的例子，也经常与用户生成内容做比较。 开
源软件的英文“open-source software”一词出自自由软件的营销活动中。开源软件同时也是一种软件的分发模式。一般的软件仅可获取已经过编译的二进制可执行档，通常只有软件的作者或著作
权所有者等拥有程序的源代码。```"

== 开源软件共同体 （Open Source software community）

为了实现一个开源软件项目，基于互联网，由企业、个人、非营利组织等形成的团体成员，在文化上能够达成一定共识，来去自由，进行一定的社会治理、活动、交流等。该共同体由计算机相关
专业领域中的工作者组成。在一种绝大多数其他领域无法比拟的程度上，他们都经受过近似的教育和专业训练。

== 开源软件基金会（ Open Source software Foundation）

由非政府的、非营利的、自有资金（通常来自单一的个人、家庭或公司）并自设董事会管理工作规划的组织，其创办的目的是为了支持发展开源软件项目，以服务于公共福利，主要途径是通过对其他
非营利机构的赞助。自身的资金来源主要是通过接受捐赠、监管下的营销、举办会议等。
