开源项目的需要基础设施的帮助。

== 邮件列表

  - 为什么开源社区使用邮件列表进行交流
在Apache社区有一个不成文的规矩：“没有在邮件列表里面发生的事情就没有发生”。邮件列表已经成为开源社区比较流行的沟通习惯了， 以笔者的日常工作为例， 使用邮件列表来进行沟通？

由于社区的成员遍布世界各地，时差是大家在沟通的过程中需要解决的一个很重要的问题。在Apache社区大部分的开发人员都居住在欧美地区，如果要大家一起坐下来开会，基本选的时间都是在东半球的开发人员睡觉的时候。例如每年举办的Apache软件基金会成员大会基本上就选在了北京时间凌晨三点左右召开。 通过邮件列表这样异步的方式可以比较好的解决时区问题，因为邮件是异步的，发件者不需要等待接收者上线就可以发送邮件，而接收者可以选择他比较方便的时间回复邮件。

当然使用邮件列表还有一个好处就是，邮件存档检索都比较方便，这样可以让关心邮件主题的朋友随时跳进来参与讨论。 我经常可以看到在Camel的用户组里有人会就几个月以前讨论的问题接着发信寻找更好的解决方案。社区成员可以通过搜索公开的存档邮件及时获取到相关的问题的讨论上下文，通过邮件列表可以极大降低社区成员获取信息的成本，让知识能够沉淀下来，这对于人员流动性比较大的开源社区来说是非常重要的。

说了这么多使用邮件列表沟通的好处，那为什么国人很少用邮件列表问问题呢？简单分析一下，可能会涉及几方面的问题。

第一是语言问题，因为在Apache社区，大家都是用英语来进行沟通， 对于大多数的开发人员来说，他们想比较快的解决问题，往往会先选择使用Baidu搜索相关的中文解决方案，而很少尝试去邮件列表里面去用英文来问问题。对于大部分和用户使用相关的问题，使用中文来检索应该能找到相关的解决方案。但是如果我们想深入研讨软件内部的细节问题的时候，使用英文往往能获取到第一手的信息。

第二可能是大家觉得邮件会比较慢， 如果邮件的讨论方正好分布在东西两个半球，一次有效的来回讨论可能就会占据一天的时间。也许正因为这种慢可以让我们在写邮件的时候可以好好考虑一下上下文的逻辑关系，以及相关讨论人的认知以及感受等问题，让大家的讨论能够比较通畅的进行下去。

现在国内的开源社区发展地也非常迅猛，大家大多会选择QQ群或者微信群等这样的及时通讯群来进行交流。这样的交流的好处是大家可以随时随地进行沟通，由于大家在这样及时通讯工具里的沟通没有相关的存档检索功能，大家的讨论很难沉淀成为能被后续加入的成员所使用的有效信息。这样表面的繁荣很难提供开源社区需要的持续发展动力。

最近在Apache孵化项目社区中就有这样有关项目建立中文QQ群的讨论，有兴趣的同学可以通过https://www.mail-archive.com/general@incubator.apache.org/msg57192.html[邮件列表存档]获取相关的内容。 当然由于这个主题涉及到多方面的内容，大家讨论的方向会比较多： 有讨论Apache是不是应该鼓励多语言讨论的，有讨论是不是邮件列表讨论是必须的。 就从方便让大家围观，及时全面了解问题的上下文的角度来说，大家应该能够体会到邮件列表的强大威力了。


	- 邮件交流的礼仪

在国内大部分开源社区的交流可能会发生在微信或者QQ群，或者是其他的论坛。为了积攒人气，有些人可能喜欢刷屏，或者灌水。但这样灌水的情况在邮件列表里面却很少发生，难道大家不喜欢凑热闹吗?

开源社区的交流是建立在志愿服务的基础上的，参与讨论的人没有任何义务要回复你的问题，大家投入时间参与讨论，是建立在一个共赢的基础上的。只要讨论的问题是大家关心的问题，大家觉得这样的讨论是有价值的，自然就会有人参与进来。试想一下，如果你通过灌水，刷屏来寻找存在感，这样的行为会让人觉得你是在浪费大家的时间，你不尊重这个讨论问题的环境，长此次下来就没有多少人愿意回答你的问题。

在开源社区中，你的名声不是靠你职位来获得，而是靠你在社区里面赢得的影响力。影响力的大小和你在社区中贡献大小有很直接的关系。如果你长期在邮件列表里面高质量地回复问题，那你在邮件列表里说话的分量就很重，你在社区的影响力就很大。正是这个原则让我们在寻找社区帮助的时候看到了很多热心的帮助者，他们不计回报地帮助你解决棘手的问题，帮助你成长。对于这样的帮助我们应该心存感激，而不是想当然的认为他们必须要帮助我。

开源社区的交流是公开的，存档的。任何人可以通过搜索引擎或者其他检索工具检索到绝大部分的交流内容来。这就意味这我们发的邮件或者是提交的评论会被很多人看到（可能是成百上千），而且我们写的内容会在很长时间内帮助其他人很快速了解事情的来龙去脉。为了提高交流的效率，在我们在问问题之前，应当检索一下是否有类似的讨论。如果有类似的讨论，我们可以选择在之前的邮件上进行回复;如果没有类似的讨论，我们可以发起一个新的邮件讨论，言简意赅地表述与主题相关的内容。

为了能让我们的问题讨论能让更多的人受益，我们应该选择用公开的邮件列表来讨论问题，而不是单独私信他人。也许你认为自己问的问题比较初级，担心在公开的邮件列表里面问这样的问题会显得自己比较业余。其实这样的担心是多余的，开源社区不会因为你问的问题简单就嘲笑你。如果你问问题之前使用搜索引擎做过一些功课之后，还是没有找到答案的话，那你的问题含金量就比较高了。如果你能问出这样有技术含量的问题的话，我相信社区大牛会很乐意回复你的问题的，很多时候开源社区的大牛要证明自己牛是需要靠这样的问题衬托出来的。

接下来和大家聊一下为什么在开源社区我们要站在中立的角度上去讨论问题。

开源社区的交流就好像是我们在一个大厅里说话一样，我们所有交谈的内容大家都能听见，而且有可能会被大家反复播放。如果这个时候我们在吵架，很有可能吸引很多的围观者。在吵架的过程中，我们可能会说出一些让我们后悔说出的话。在平日里这些话可能不会那么刺耳，因为大家可能会很快忘却。但是如果在开源社区，这样伤人的话会作为永久的记录保存下来，而且会被大家随时检索出来。为了让我们的描述足够客观，避免被别人错误理解， 我们也需要注意表达的语气。如果我们在写信的时候，情绪比较激动话，可以选择把过半天或者一天之后在自己情绪不那么激动的时候写信。如果我们在邮件列表里面看到相关的攻击，不要选择加入类似的攻击，而是站在一个比较客观的中立角度来阐述问题。

	- 依托的服务

== 版本控制系统

=== 版本控制系统简介

include::vcs/VCS-introduciton.adoc[]

=== Git 之前的版本控制系统

include::vcs/era-git-vcs.adoc[]

=== Git

include::vcs/git-introduction.adoc[]

== 代码仓库

	- 代码仓库的基本功能

	- 常见代码仓库的使用

== 项目资料

	- 创建网站

项目本身是需要向世人展示的，在互联网如此发达的今天，如果一个开源项目没有相应的可以使用搜索引擎搜得到的站点，那么很可能潜在的用户和开发者都找不到你的项目。鉴于目前代码协作平台如GitHub等强大的功能，我们特别说明建立网站通常有三种方式：

一、 GitHub Page



二、 自行搭建


三、 第三方托管



	- 网站工具

一、SEO （搜索引擎优化）




	- 编写用户手册

要为你的项目最终的输出物：软件，编写用户使用手册。


== 持续集成系统

=== 持续集成功能与意义

=== Jenkins集成

=== Travis，Github Actions 在线服务

随着web的发展，越来越多的服务可以通过友好的API来进行实现，相比于 Jenkins 部署本地的服务，对于很多项目其实是没有必要的，‘随需随用’、毋需维护基础设施成本、和GitHub等开放式开发平台无缝集成，为什么要拒绝了呢？下面我们就以两个实例为说明持续集成的在线服务。

==== Travis



==== GitHub Action



== 问题追踪系统

=== 问题追踪的功能

=== 常见的问题追踪系统的使用

==== Bugzilla

==== Jira


==== GitHub Issue


==== Trac issue


== 现代开源项目开发集大成者 GitHub 平台介绍

include::github-introduction.adoc[]
