= 开源手册
姜宁 <ningjiang@apache.org>
2020-05-04
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
:doctype: book
:page-layout!:
:toc: left
:toclevels: 2
:sectanchors:
:sectlinks:
:sectnums:
:icons: font
:source-highlighter: coderay
:source-language: asciidoc
:experimental:
:stem:
:idprefix:
:idseparator: -
:ast: &ast;
:dagger: pass:normal[^&dagger;^]
:endash: &#8211;
:y: icon:check[role="green"]
:n: icon:times[role="red"]
:c: icon:file-text-o[role="blue"]
:table-caption!:
:example-caption!:
:figure-caption!:
:imagesdir: ../images
:includedir: _includes
:underscore: _
:adp: AsciiDoc Python
:adr: Asciidoctor

这是一本通过开源的方式撰写的指导手册，在这里我们将依托社区的力量帮助大家了解开源协作的背景知识，介绍相关的协作开发工具，以及开源协作中的最佳实践。

在二十年前，link:https://en.wikipedia.org/wiki/Open_source[开源（Open Source）]这一词汇被 link:https://opensource.org[Open Source Initiative] 提出。随着越来越多的开源项目成为我们信息化社会的基石，开源作为一个高效的软件协同开发方式逐渐被世人接受。开源的本质是开放与协作，人们可以借助开源的手段开发软件，开发硬件，编写手册。

以往我们作为开源的消费方，开源项目更像是一份免费的午餐，我们不需要知道午餐是怎么做出来的，我们只需要吃好这份午餐（了解开源项目是如何使用）就可以了；随着我们成为"免费午餐"的生产方，通过开源来为我们创新的步伐助力的时候，急切需要有一份详尽的开源手册帮助大家掌握开源项目实际操作的知识与技能。

 * 如果你刚刚接触开源，可以从手册中开源的文化背景，开源协作的社交礼仪入手，通过参与现实的开源社区项目来体验开源的魅力。
 * 如果你有一个不错的想法来解决业界的难题，并且想通过开源项目的方式邀请更多与你有同样想法的人与你协作的话，本手册将向你介绍如何依托市面的开源工具以及协作平台来提高开源协作效率。
 * 如果你正在为开源项目运营而苦恼，那通过本手册你将会了解如何通过透明公开方式来孕育社区项目，让项目具备持续发展的生命力。
 * 如果你有不错的开源项目运营经验想跟我们分享你的心得，本手册将是你展示自我风采的舞台，欢迎通过邮件，issue，PR的方式分享你的心得。

这是一本探讨社区协作的开源手册，我们也将会采用社区协作的方式来完善这本手册。如果你觉得这本手册的立意不错，欢迎加入我们的 link:https://github.com/willemjiang/open-source-manual/issues[讨论区]，通过创建issue的方式反馈你的意见建议，通过PR的方式帮助我们修正手册中的错误。
最后希望这本手册很够帮助到更多想实际参与到开源项目开发的人们。

= 准备开源
include::Preparation.adoc[]

= 基础设施
include::Infranstruction.adoc[]

= 开源质量
include::OpenSourceQA.adoc[]

= 开源协作
include::Collaboration.adoc[]
