== 开源最佳实践
=== 上游优先的开发方式
开源项目之间是相互依赖包含构成了一个完整的生态体系。一个开源项目可能会使用到很多第三方的开源项目，这个开源项目也可能被第三方项目引用包含到其它的开源或者非开源的项目中。通常我们会把被依赖的项目称为上游项目，对上游项目产生依赖的项目为下游项目。上游项目提供了具体的功能实现，下游项目一般通过调用上游项目实现相关的功能。

上游优先的开发式是指开源开发者为了实现自己的需求把对上游项目的修改都回合到上游社区项目中，通过升级上游项目版本的方式获取最新的功能， 而不是只是在自己的项目中进行自己的需求修改。这样做有以下方面的好处：

* 把代码修改合入上游，维护成本最低的协作方式。

开源项目的有很多的贡献者，大家之所以能够在一起协作的根基是代码开放的， 这样每个人都可以在别人的基础上添加自己的工作。为了达到高效的协作需要保证大家的相互修改不应该产生副作用，或者说我们需要有一个协调机制保证大家修改过的代码放在一起还能够工作。 如果大家把修改都提交到一个上游版本中，在代码提交之前只需要一次解决修改冲突问题，这是最省力也是最有效的协作方式。

Fork上游代码看上去挺简单的，我的修改我做主。但是从fork的那天开始你就要背负维护这个fork版本的生老病死的所有的责任。一旦你的代码与上游代码差异越大， 你的代码想要合并上游的更新的代价也就越大。这样带来的直接问题就是无法及时享受到上游代码更新带来的好处。 明智的开发往往会在自己修改代码之后，努力将自己的修改推进上游代码以降低自己的维护成本。

* 回合上游代码之后，随时可以使用上游代码的最新更新。

上游项目发布新版本了，我能在第一时间将上游项目集成到我的扩展项目中吗？这个和你如何引用上游代码有很大的关系。 一般来说如果你只是片段引用上游代码或者直接fork上游代码， 你需要自己做所有的修改适配。如果上游项目发展不是很快的话，你可以能花几天的时间就适配好了，但是如果项目发展很快，三个月出一个版本的话，你的适配步伐很难跟上上游的开发速度的。 一般来说fork版本的维护只有一个人， 而上游的开发可能是4~5个人， 同时社区还会有很多贡献者也在合入代码， 在这种情况下fork之后的版本往往采用的方式就是不会合入上游新开发的特性和功能的而自己独自地走下去。

如果你还想继续享受到上游开发带来的好处， 请将你的代码回合到上游代码中，因为这样做你仍然可以以0成本的方式使用上游最新的代码。

* 回合上游代码，可以让更多的人受益，推动项目成功。

众人拾柴火焰高， 一个成功的开源项目背后必然有一个蓬勃发展的社区。依托于社区我们可以做到很多平时一个人在公司无法实现的目标。 在开源项目社区中，大家共同的目标就是把这款开源软件做得更好。这里有用户报系统的bug，有贡献者将自己的使用心得转换成patch提到社区中了，有维护人员不断的添加新的功能并及时得到用户的反馈而又继续开发更炫酷的功能。开源项目依托于社区只所以可以不断发展壮大，正因为大家是相互协作的，力气都往一处使，每个人在贡献自己的力量的同时也为大家节省了很多开发协作的时间，依托于一个社区大家可以共享工作成果。 假如你想借助开源完善丰富你的产品的话，维护一个统一的社区比将社区分裂要好很多。

=== 可插拔软件体系架构

=== MVP原则

=== 撰写有吸引力README文档

== 知识产权与合规

=== 版权基础知识

=== 开源License的选择

=== 第三方依赖License

== 项目命名与商标

=== 项目命名

=== 商标注册

=== 域名申请
