

==== RCS

RCS 是由普渡大学的 Walter F. Tichy 教授在1982年所开发。主要语言采用的是C语言。

RCS对文件进行集中式管理，主要目的是避免多人合作情况下可能出现的冲突。如果多用户同时写入同一个文件，其写入结果可能相互混合和覆盖，从而造成结果的混乱。你可以将文件交给RCS管理。RCS允许多个用户同时读取文件，但只允许一个用户锁定(locking)并写入文件 (类似于多线程的mutex)。这样，当一个程序员登出(check-out，见RCS的co命令)某个文件并对文件进行修改的时候。只有在这个程序完成修改，并登入(check-in，见RCS的ci命令)文件时，其他程序员才能登出文件。基本上RCS用户所需要的，就是co和ci两个命令。在co和ci之间，用户可以对原文件进行许多改变(change, or file delta)。一旦重新登入文件，这些改变将保存到RCS系统中。通过check-in将改变永久化的过程叫做提交(commit)。



==== 古老的 CVS

> 要弄明白为什么 Git 的分布式特性是对以前的版本控制系统的极大改善的话，除了折腾 CVS 外，没有更好的办法。 -- Two-bit History

接下来我们引用《CVS精髓》一书当中对于CVS 的解释：

CVS 是一种版本跟踪系统，它可以在软件开发过程中保持文件的各种记录以及取出文件的任何已被存储的版本，制作出各种版本的软件。CVS 可以让多名开发人员同时编辑单一文件而不会遗失任何数据。每名开发人员各自编辑自己所拥有的该文件的副本，最后所有的修改会合并到单一的主“副本”中。CVS
所提供的功能可以协助项目经理跟踪项目随时间而变的轨迹。



==== 拥有完整权限控制的 SVN

SVN 真正的项目名称叫做： http://subversion.apache.org[Subversion]，目前是 Apache 软件基金会下的顶级项目，在分布式系统Git流行之前，SVN 是开源当中最佳的选择。至于其为什么被业内人士经常简称为svn，大约是命令行为svn 的缘故吧，我们在下文或本书中也会多次提到SVN，
它没有特别申明的情况下就是指 Subversion。

SVN 由 CollabNet 公司于2000年资助并开发，目标就是创建一个更好用的版本控制系统以取代CVS，

==== 参考资料

1. 《CVS精髓》，Jennifer Vesperman 著，东南大学出版社，ISBN: 9787564102555，出版年: 2006-4
